name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: latest
      - run: pnpm install --ignore-scripts
      - run: pnpm run lint
      - run: pnpm run check
  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: latest
      - run: pnpm install --ignore-scripts
      - run: pnpm run test
